# Generated by Django 4.2.1 on 2023-07-02 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.PositiveSmallIntegerField(verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='DeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
            },
        ),
        migrations.CreateModel(
            name='EducationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Год',
                'ordering': ('year',),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('education_form', models.CharField(choices=[('Kunduzgi', 'Дневное'), ('Kechki', 'Вечернее')], max_length=32, verbose_name='Форма обучения')),
                ('language', models.CharField(choices=[('O‘zbek', 'Узбекский'), ('Rus', 'Русский')], max_length=32, verbose_name='Язык обучения')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hours', models.PositiveSmallIntegerField(verbose_name='Часы')),
                ('lecture_hours', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Часы (Лекция)')),
                ('practice_hours', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Часы (Практика)')),
                ('seminar_hours', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Часы (Семинар)')),
                ('laboratory_hours', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Часы (Лабораторная)')),
                ('independent_hours', models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Часы (Самостоятельное обучение)')),
                ('credits', models.PositiveSmallIntegerField(verbose_name='Кредиты')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('hemis_id', models.CharField(max_length=255, unique=True, verbose_name='Hemis ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Semestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestr', models.PositiveSmallIntegerField(verbose_name='Семестр')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестры',
                'ordering': ['semestr'],
            },
        ),
        migrations.CreateModel(
            name='KontraktAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='credits.direction')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.faculty', verbose_name='Факультет'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_hours', models.PositiveSmallIntegerField(verbose_name='Часы за год')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('DEANERY_UPLOADED', 'Загружено деканатом'), ('FINANCE_SETTED', 'Цена кредита утверждена'), ('DEANERY_SETPAID', 'Оплатил'), ('ACCOUNTANT_SUBMITED', 'Подтверждено бухгалтером')], default='DEANERY_UPLOADED', max_length=64)),
                ('edu_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credits.educationyear')),
                ('semestr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credits.semestr')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credits.subject')),
            ],
        ),
    ]
