# Generated by Django 4.2.1 on 2023-11-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['id'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours',
            field=models.PositiveSmallIntegerField(default=None, null=True, verbose_name='Часы'),
        ),
    ]
