# Generated by Django 4.2.1 on 2023-07-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['student__name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AddField(
            model_name='payset',
            name='incoice',
            field=models.FileField(null=True, upload_to='files/invoices/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='group',
            name='education_form',
            field=models.CharField(choices=[('Kunduzgi', 'Дневное'), ('Kechki', 'Вечернее'), ("Qo'shma", 'Смешанное')], max_length=32, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='group',
            name='language',
            field=models.CharField(choices=[('O‘zbek', 'Узбекский'), ('Rus', 'Русский'), ('Tojik', 'Таджикский'), ('Ingliz', 'Английсикй')], max_length=32, verbose_name='Язык обучения'),
        ),
    ]
