# Generated by Django 4.2.1 on 2023-07-03 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='faculty',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='credits.faculty', verbose_name='Факультет'),
        ),
        migrations.AddField(
            model_name='deadline',
            name='for_accountant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deadline',
            name='for_finances',
            field=models.BooleanField(default=False),
        ),
    ]
