# Generated by Django 4.2.1 on 2023-07-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_credit_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payset',
            old_name='incoice',
            new_name='invoice',
        ),
    ]
