# Generated by Django 4.2.1 on 2023-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_alter_group_options_alter_subject_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.FloatField(verbose_name='Кредиты'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
