# Generated by Django 4.2.1 on 2023-11-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_subject_credits_alter_subject_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.FloatField(null=True, verbose_name='Кредиты'),
        ),
    ]
