# Generated by Django 4.2.1 on 2023-11-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_alter_subject_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Загружено с HEMIS'), ('DEANERY_UPLOADED', 'Загружено деканатом'), ('FINANCE_SETTED', 'Цена кредита утверждена'), ('DEANERY_SETPAID', 'Оплатил'), ('ACCOUNTANT_SUBMITED', 'Подтверждено бухгалтером')], default='DEANERY_UPLOADED', max_length=64),
        ),
        migrations.AlterField(
            model_name='subject',
            name='credits',
            field=models.FloatField(default=0, verbose_name='Кредиты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='hours',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Часы'),
            preserve_default=False,
        ),
    ]
