# Generated by Django 4.2.1 on 2023-11-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_credit_status_alter_subject_credits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='education_form',
        ),
        migrations.AddField(
            model_name='direction',
            name='edu_hours',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='direction',
            name='education_form',
            field=models.CharField(default='k', max_length=32, verbose_name='Форма обучения'),
            preserve_default=False,
        ),
    ]
