# Generated by Django 4.2.1 on 2023-11-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0006_remove_group_education_form_direction_edu_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_semestr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_for_last', to='credits.semestr'),
        ),
        migrations.AddField(
            model_name='credit',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
