# Generated by Django 4.2.1 on 2023-11-18 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0008_alter_course_last_semestr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_semestr',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_for_last', to='credits.semestr'),
        ),
    ]
